
```{r}
# install.packages(c("readr","data.table","reshape2","dplyr","tidyr"))

```

```{r}
zip.directory <- '../data'
raw.directory <- paste0(zip.directory,'/raw.files')
proc.directory <- paste0(zip.directory,'/processed')

expected_cols <- list(
  transiat = c("log_serial","trial_id","name","responseHandle","latency","stimuli","media","data.blockStart","data.condition","data.score","data.block","sessionId","data.parcel","data.corResp","block3Cond","feedback","d"),
  
  ds_r = c("name","response","serial","latency","pristineLatency","declined","submitLatency","sessionId"),
  
  tabs = c("name","response","serial","latency","pristineLatency","declined","submitLatency","sessionId"),
  
  explicits = c("name","response","serial","latency","pristineLatency","declined","submitLatency","sessionId"),
  
  unnamedTask = c("`$isTouch`","sessionId")
)
```


# Read all the data files

```{r}
# Load the readr package
library(readr)

# Define the name of the zip file (that the storage download from the osf)
zip_file <- paste0(zip.directory,"/osfstorage-archive.zip")

# Create the directories
dir.create(raw.directory, showWarnings = TRUE, recursive = TRUE)
dir.create(proc.directory, showWarnings = FALSE, recursive = TRUE)
# List the files in the zip file
files <- unzip(zip_file, list = TRUE, exdir = raw.directory)$Name

# Extract the prefixes from the file names
prefixes <- sub("_[^_]+\\.csv$", "", files)

# Create an empty list to store the data frames
data_list <- list()

# Loop over the unique prefixes

for (p in unique(prefixes)) {
  
  p_files <- files[prefixes == p]
  
  dfs <- lapply(p_files, function(f) {
    
    # Extract ONE file and get its path
    extracted_path <- unzip(zip_file, files = f, exdir = raw.directory)
    
    # Read that one file
    readr::read_csv(
      extracted_path,
      col_types = readr::cols(.default = "c"),
      show_col_types = FALSE
    )
  })
  # filter only the wanted columns
  dfs <- lapply(dfs, function(df) {
    
    # Drop fbclid and any other unexpected columns
    df$fbclid <- NULL
    
    # Add missing expected columns
    missing <- setdiff(expected_cols[[p]], names(df))
    df[missing] <- NA
    
    # Keep only expected columns, in correct order
    df <- df[expected_cols[[p]]]
    
    df
  })
  
  # Safe row-bind (fills missing columns with NA)
  p_data <- dplyr::bind_rows(dfs)
  
  data_list[[p]] <- p_data
}


# for (p in unique(prefixes)) {
#   # Filter the files that match the prefix
#   p_files <- files[prefixes == p]
  
#   # Read the files into a data frame
#   p_data <- read_csv(unzip(zip_file, p_files, exdir = raw.directory))
  
#   # Rbind the columns
#   p_data <- do.call(rbind, p_data)
  
#   # Add the data frame to the list with the prefix as the name
#   data_list[[p]] <- p_data
# }
```
# Process IAT

```{r}
##Read all the IAT data files.
raw.iat <- data_list[['transiat']]
```

```{r}
# Preprocessing for the IAT scoring function.

raw.iat$blockName <- ifelse(raw.iat$data.condition %in% c('Transpersonas/Slikti vārdi,Cispersonas/Labi vārdi'), 
                        ifelse(raw.iat$data.block %in% c(3,6), 'B3', 
                               ifelse(raw.iat$data.block %in% c(4,7), 'B4', NA)), 
                        ifelse(raw.iat$data.condition %in% c('Cispersonas/Slikti vārdi,Transpersonas/Labi vārdi'), 
                          ifelse(raw.iat$data.block %in% c(3,6), 'B6', 
                                 ifelse(raw.iat$data.block %in% c(4,7), 'B7', NA)), NA))
# table(raw.iat$blockName, exclude=NULL)
```

```{r}
class(raw.iat$latency)
#If the latency is not numeric, convert to numeric
raw.iat$trial_latency <- as.numeric(as.character(raw.iat$latency))
range(raw.iat$trial_latency, na.rm=T)
table(raw.iat$latency[which(is.na(raw.iat$trial_latency))], exclude=NULL)

class(raw.iat$data.score) #data.score is 0 if the response was correct, and 1 if it was an error.
#If the error variable is not numeric, convert to numeric
raw.iat$trial_error <- as.numeric(as.character(raw.iat$data.score))
table(raw.iat$trial_error, exclude=NULL)

```
```{r}
# raw.iat$trial_correct <- 1-raw.iat$trial_error
```
```{r}
source('./score_IAT.r')

score <- score_IAT(raw.iat)
# table(score)
write.csv(score, paste(proc.directory, 'iat.csv', sep='/'))
```

# Process the self-report questionnaire

```{r}
for.qst <- data_list[['explicits']]

class(for.qst$response)
#Convert to numeric
for.qst$resp <- as.numeric(as.character(for.qst$response))
#Convert -999 to NA; Notice that we lose here information about the rare of skipping questions.
for.qst$resp <- ifelse(for.qst$resp==-999, NA, for.qst$resp)

table(for.qst$name)

library(data.table)
dups <- setDF(setDT(for.qst)[, if (.N > 1L) .SD, by=.(sessionId, name)])
dup.sids <- dups$sessionId
for.exp <- for.qst[which(!for.qst$sessionId %in% dup.sids),c('sessionId','name','resp')]


library(reshape2)

qst <- reshape2::dcast(data = for.qst, formula = sessionId ~ name, value.var = 'resp')

write.csv(qst, paste(proc.directory, 'qst.csv', sep='/'))
```

# Process the DS_R questionnaire

```{r}
for.dsr <- data_list[['ds_r']]

class(for.dsr$response)
#Convert to numeric
for.dsr$resp <- as.numeric(as.character(for.dsr$response))
#Convert -999 to NA; Notice that we lose here information about the rare of skipping questions.
for.dsr$resp <- ifelse(for.dsr$resp==-999, NA, for.dsr$resp)

table(for.dsr$name)

library(data.table)
dups <- setDF(setDT(for.dsr)[, if (.N > 1L) .SD, by=.(sessionId, name)])
dup.sids <- dups$sessionId
for.exp <- for.dsr[which(!for.dsr$sessionId %in% dup.sids),c('sessionId','name','resp')]

library(reshape2)

dsr <- reshape2::dcast(data = for.exp, formula = sessionId ~ name, value.var = 'resp')

write.csv(dsr, paste(proc.directory, 'dsr.csv', sep='/'))
```

# Process the TABS questionnaire

```{r}
for.tabs <- data_list[['tabs']]

class(for.tabs$response)
#Convert to numeric
for.tabs$resp <- as.numeric(as.character(for.tabs$response))
#Convert -999 to NA; Notice that we lose here information about the rare of skipping questions.
for.tabs$resp <- ifelse(for.tabs$resp==-999, NA, for.tabs$resp)

table(for.tabs$name)

library(data.table)
dups <- setDF(setDT(for.tabs)[, if (.N > 1L) .SD, by=.(sessionId, name)])
dup.sids <- dups$sessionId
for.exp <- for.tabs[which(!for.tabs$sessionId %in% dup.sids),c('sessionId','name','resp')]

library(reshape2)

tabs <- reshape2::dcast(data = for.exp, formula = sessionId ~ name, value.var = 'resp')

write.csv(tabs, paste(proc.directory, 'tabs.csv', sep='/'))
```

# Read conditions

  ```{r}
  conds <- data_list[['unnamedTask']]
  blockOrder <- raw.iat[which(!is.na(raw.iat$block3Cond)),c('sessionId','block3Cond')]

  blockOrder$iat.order <- ifelse(blockOrder$block3Cond %in% c('Transpersonas/Slikti vārdi,Cispersonas/Labi vārdi'), 
                          'compatibleFirst', 
                          ifelse(blockOrder$block3Cond %in% c('Cispersonas/Slikti vārdi,Transpersonas/Labi vārdi'), 
                            'incompatibleFirst', NA))
  table(blockOrder$iat.order, exclude=NULL)

  conds <- merge(conds, blockOrder, by='sessionId', all = T)
  write.csv(conds, paste(proc.directory, 'conds.csv', sep='/'))
  ```

# Merge all processed data

```{r}
iat <- read.csv(paste(proc.directory, 'iat.csv', sep='/'))
qst <- read.csv(paste(proc.directory, 'qst.csv', sep='/'))
conditions <- read.csv(paste(proc.directory, 'conds.csv', sep='/'))
dsr <- read.csv(paste(proc.directory, 'dsr.csv', sep='/'))
tabs <- read.csv(paste(proc.directory, 'tabs.csv', sep='/'))
```
```{r}

iat_pref <- iat %>%
  dplyr::select(sessionId, IAT, IAT1, IAT2) %>%
  dplyr::rename_with(~ paste0("iat_", .x), -sessionId)

dsr_pref <- dsr %>%
  dplyr::rename_with(~ paste0("dsr_", .x), -sessionId)

tabs_pref <- tabs %>%
  dplyr::rename_with(~ paste0("tabs_", .x), -sessionId)

personal_pref <- qst %>%
  dplyr::rename_with(~ paste0("personal_", .x), -sessionId)

conditions_pref <- conditions %>%
  dplyr::rename_with(~ paste0("conditions_", .x), -sessionId)

```

```{r}
# all <- merge(iatscores, selfReport, by='sessionId', all = T)
# all <- merge(all, conditions, by='sessionId', all = T)

all <- iat_pref %>%
  merge(conditions_pref, by = "sessionId") %>%
  merge(personal_pref,  by = "sessionId") %>%
  merge(dsr_pref,    by = "sessionId") %>%
  merge(tabs_pref,   by = "sessionId")
print(all)
write.csv(all, paste(proc.directory, 'all.csv', sep='/'))

```

```{r}
#cor(all$IAT, all$attributes7, use = "complete.obs")
```

